# Generated by Django 6.0.7 on 2026-07-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'consultant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.profile'),
        ),
    ]
