# Generated by Django 6.0.7 on 2026-07-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date']},
        ),
    ]
